name: 'identity_service'

services:
  
  domic.auth.api:
    networks:
      - domic
    image: identity_service:1.0.0
    # deploy:
    #   resources:
    #     limits:
    #       memory: 150M
    #     reservations:
    #       memory: 150M
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "1040-1060:443"
    volumes:
      - log:/app/CoreLogs
      - ~\.aspnet\https\:/https/
    environment:
      - Elastic-Host=http://domic.elastic.search:9200
      - Elastic-Index=identity
      - Elastic-Username=domic
      - Elastic-Password=Domic123!@#
      - E-RabbitMQ-Host=domic.rabbit.mq
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=domic
      - E-RabbitMQ-Password=Domic123!@#
      - I-RabbitMQ-Host=
      - I-RabbitMQ-Port=
      - I-RabbitMQ-Username=
      - I-RabbitMQ-Password=
      - E-RedisConnectionString=
      - I-RedisConnectionString=
      - MongoConnectionString=
      - C-SqlServerConnectionString=Server=domic.identity.command.sql.server,1433;Database=C-IdentityService;User ID=sa;Password=Hasan313@@313!!;MultipleActiveResultSets=true;
      - Q-SqlServerConnectionString=Server=domic.identity.query.sql.server,1433;Database=Q-IdentityService;User ID=sa;Password=Hasan313@@313!!;MultipleActiveResultSets=true;
      - Host=domic.identity.api
      - Port=443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Domic123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Domic.WebAPI.pfx
    depends_on:
      - domic.identity.command.sql.server
      - domic.identity.query.sql.server
  
  domic.identity.command.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'command_identity_sql_server'
    ports:
      - 1439:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hasan313@@313!!

  domic.identity.query.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'query_identity_sql_server'
    ports:
      - 1499:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hasan313@@313!!

volumes:
  log:
    
networks:
  domic:
    external: true