name: 'identity_service'

services:
  
  domic.identity.service:
    networks:
      - domic
    image: domic_identity_service_image:1.0.0
    container_name: "domic_identity_service"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 150M
    #     reservations:
    #       memory: 150M
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "1040-1060:443"
    volumes:
      - ~/services/Logs/Domic-IdentityService/:/app/CoreLogs/
      - ~/services/Domic-IdentityService/.https/:/https/
    environment:
      - Elastic-Host=http://domic.elastic.search:9200
      - Elastic-Index=identity
      - Elastic-Username=domic
      - Elastic-Password=Domic123!@#
      - E-RabbitMQ-Host=domic.rabbit.mq
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=domic
      - E-RabbitMQ-Password=Domic123!@#
      - I-RabbitMQ-Host=
      - I-RabbitMQ-Port=
      - I-RabbitMQ-Username=
      - I-RabbitMQ-Password=
      - E-RedisConnectionString=domic.redis:6379
      - I-RedisConnectionString=domic.redis:6379
      - MongoConnectionString=
      - C-SqlServerConnectionString=Server=domic.sql.server,1433;Database=C-IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;
      - Q-SqlServerConnectionString=Server=domic.sql.server,1433;Database=Q-IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True;
#     - C-SqlServerConnectionString=Server=domic.identity.command.sql.server,1433;Database=IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Encrypt=False;
#     - Q-SqlServerConnectionString=Server=domic.identity.query.sql.server,1433;Database=IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Encrypt=False;
      - Host=domic.identity.service
      - Port=443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Domic123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Domic.WebAPI.pfx
  
#   depends_on:
#     - domic.identity.command.sql.server
#     - domic.identity.query.sql.server
  
#   domic.identity.command.sql.server:
#     networks:
#       - domic
#     image: 'mcr.microsoft.com/mssql/server'
#     container_name: 'domic_command_identity_sql_server'
#     deploy:
#       resources:
#         limits:
#           memory: 2G
#     ports:
#       - 1439:1433
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Domic123!@#
  
#   domic.identity.query.sql.server:
#     networks:
#       - domic
#     image: 'mcr.microsoft.com/mssql/server'
#     container_name: 'domic_query_identity_sql_server'
#     deploy:
#       resources:
#         limits:
#           memory: 2G
#     ports:
#       - 1499:1433
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Domic123!@#
    
networks:
  domic:
    external: true